/************************************************************************************************/
/*	███╗   ███╗ █████╗ ██╗  ██╗███████╗    ███╗   ███╗██╗   ██╗    ███████╗██╗██╗     ███████╗	*/
/*	████╗ ████║██╔══██╗██║ ██╔╝██╔════╝    ████╗ ████║╚██╗ ██╔╝    ██╔════╝██║██║     ██╔════╝	*/
/*	██╔████╔██║███████║█████╔╝ █████╗      ██╔████╔██║ ╚████╔╝     █████╗  ██║██║     █████╗  	*/
/*	██║╚██╔╝██║██╔══██║██╔═██╗ ██╔══╝      ██║╚██╔╝██║  ╚██╔╝      ██╔══╝  ██║██║     ██╔══╝  	*/
/*	██║ ╚═╝ ██║██║  ██║██║  ██╗███████╗    ██║ ╚═╝ ██║   ██║       ██║     ██║███████╗███████╗	*/
/* 	╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝    ╚═╝     ╚═╝   ╚═╝       ╚═╝     ╚═╝╚══════╝╚══════╝	*/
/************************************************************************************************/

#include "make_my_file.h"
#include "write_in_file.h"

void generate_makefile(t_make_config *config)
{
	FILE *file = fopen("Makefile", "w");
	if (!file)
	{
		printf("Error.\n Could not create Makefile.\n");
		return;
	}

	/*** PRINT DOC ***/
	time_t now = time(NULL);
	struct tm *local_time = localtime(&now);
	fprintf(file, "# Makefile generated by Make My File: https://github.com/MathysCogne/Make_My_File-42\n");
	fprintf(file, "# Date of generation: %02d-%02d-%04d %02d:%02d:%02d\n\n", local_time->tm_mday, local_time->tm_mon + 1, local_time->tm_year + 1900, local_time->tm_hour, local_time->tm_min, local_time->tm_sec);
	fprintf(file, MAKEFILE_DOC); // TODO REFAIRE UNE DOC A JOUR AVEC LES MAJ

	/*** INCLUDE HEADER DEFINE ***/
	fprintf(file, "NAME = %s\n\n", config->name);

	fprintf(file, "SRCDIR = %s\n", config->src_dir);
	fprintf(file, "OBJDIR = %s\n", config->obj_dir);
	fprintf(file, "INCDIR = %s\n\n", config->header_dir);

	/*** SRC FILES DEFINE ***/
	fprintf(file, "# Source Files\n");
	fprintf(file, "SRC = %s\n", config->src_files);
	fprintf(file, "OBJ = $(SRC:.c=.o)\n");

	fprintf(file, "SRC := $(addprefix $(SRCDIR)/, $(SRC))\n");
	fprintf(file, "OBJ := $(patsubst $(SRCDIR)/%%, $(OBJDIR)/%%, $(OBJ))\n\n");

	/*** BONUS FILES DEFINE ***/
	if (config->src_file_bonus && strlen(config->src_file_bonus) > 0)
	{
		fprintf(file, "# Bonus Files\n");
		fprintf(file, "BONUS_SRC = %s\n", config->src_file_bonus);
		fprintf(file, "BONUS_OBJ = $(BONUS_SRC:.c=.o)\n\n");

		fprintf(file, "BONUS_SRC := $(addprefix $(SRCDIR)/, $(BONUS_SRC))\n");
		fprintf(file, "BONUS_OBJ := $(addprefix $(OBJDIR)/, $(notdir $(BONUS_OBJ)))\n\n");
	}

	/*** LIBFT DEFINE ***/
	if (config->include_libft)
	{
		fprintf(file, "# Libft - Please configure your own path if different\n");
		fprintf(file, "LIBFT_DIR := libft\n");
		fprintf(file, "LIBFT := $(LIBFT_DIR)/libft.a\n");
		fprintf(file, "LIBFT_INCLUDE := $(LIBFT_DIR)#/include Your header file in include dir ?\n");
	}

	/*** MINILIBX DEFINE ***/
	if (config->include_mlx)
	{
		fprintf(file, "# MiniLibx -> Please include in header file: #include \"mlx.h\"\n");
		fprintf(file, "MINILIBX_DIR := ./minilibx-linux\n");
		fprintf(file, "MLX := $(MINILIBX_DIR)/libmlx.a\n");
	}

	/*** LIBRAIRIES AND LINKER FLAGS DEFINE ***/
	fprintf(file, "# Libraries and Linker Flags\n");
	fprintf(file, "LDFLAGS = %s", 
	(config->ldflags && strlen(config->ldflags) > 0) ? config->ldflags : "");
	if (config->include_mlx)
		fprintf(file, " -L$(MINILIBX_DIR)");
	if (config->include_libft)
		fprintf(file, " -L$(LIBFT_DIR)");

	fprintf(file, "\nLIBS = %s", (config->libs && strlen(config->libs) > 0) ? config->libs : "");
	if (config->include_mlx)
		fprintf(file, " $(MLX)");
	if (config->include_libft)
		fprintf(file, " $(LIBFT)");

	fprintf(file, "\n\n# Archiver\n");
	fprintf(file, "AR = ar\n");
	fprintf(file, "ARFLAGS = rcs\n");

	/*** COMPILER AND FLAGS DEFINE ***/
	fprintf(file, "\n# Compiler and Flags\n");
	fprintf(file, "CC = %s\n", config->compiler);
	fprintf(file, "CFLAGS = %s -I$(INCDIR) -g3", config->cflags ? config->cflags : "-Wall -Wextra -Werror");
	if (config->include_mlx)
		fprintf(file, " -I$(MINILIBX_DIR) -I/usr/include/X11");
	if (config->include_libft)
		fprintf(file, " -I$(LIBFT_INCLUDE)");

	if (config->include_mlx)
	{
		fprintf(file, "\n\n# Detect OS for Flags MiniLibx\n");
		fprintf(file, "UNAME_S := $(shell uname -s)\n");
		fprintf(file, "ifeq ($(UNAME_S),Linux)\n");
		fprintf(file, "\tMLXFLAGS += -lmlx -lXext -lX11\n");
		fprintf(file, "else ifeq ($(UNAME_S),Darwin)\n");
		fprintf(file, "\tMLXFLAGS += -L/opt/X11/lib -lX11 -lXext -lXrandr -lXcursor\n");
		fprintf(file, "endif\n\n");
	}

	/*** SILENCE COMPILATION ***/
	fprintf(file, "# Compilation mode (silent by default, set VERBOSE=1 to show commands)\n");
	fprintf(file, "VERBOSE ?= 0\n");
	fprintf(file, "ifeq ($(VERBOSE),1)\n");
	fprintf(file, "  V := \n");
	fprintf(file, "else\n");
	fprintf(file, "  V := @\n");
	fprintf(file, "endif\n\n");

	/*** COLORS ***/
	fprintf(file, "# Colors\n");
	fprintf(file, "RED     := \"\\033[1;31m\"\n");
	fprintf(file, "GREEN   := \"\\033[1;32m\"\n");
	fprintf(file, "RESET   := \"\\033[0m\"\n\n\n\n");

	/*** DEFAULT | ALL RULE ***/
	fprintf(file, "# Default Rule\n");
	fprintf(file, "all: $(OBJDIR)");
	if (config->include_mlx)
		fprintf(file, " $(MINILIBX_DIR)");
	if (config->include_libft)
		fprintf(file, " $(LIBFT)");
	fprintf(file, " $(NAME)");

	/*** OBJECT DIR RULE ***/
	fprintf(file, "\n\n# Object Directory Rule\n");
	fprintf(file, "$(OBJDIR):\n");
	fprintf(file, "\t$(V)mkdir -p $(OBJDIR) || true\n\n");

	/*** DEPENDENCIES ***/
	if (config->create_dependencies)
	{
		fprintf(file, "# Dependency Files\n");
		fprintf(file, "DEP = $(OBJ:.o=.d)\n\n");

		fprintf(file, "$(OBJDIR)/%%.o: $(SRCDIR)/%%.c | $(OBJDIR)\n");
		fprintf(file, "\t@mkdir -p $(dir $@)\n");
		fprintf(file, "\t$(V)$(CC) $(CFLAGS) -MMD -MP -c $< -o $@\n\n");

		fprintf(file, "-include $(DEP)\n\n");
	}

	/*** LINKING RULE ***/
	fprintf(file, "# Linking Rule\n");
	fprintf(file, "$(NAME): $(OBJ)");
	if (config->src_file_bonus && strlen(config->src_file_bonus) > 0)
		fprintf(file, " $(BONUS_OBJ)");
	if (config->include_libft)
		fprintf(file, " $(LIBFT)");
	fprintf(file, "\n");
	/* LIB */
	if (config->create_lib_or_exec == 1)
	{
		fprintf(file, "\t$(V)$(AR) $(ARFLAGS) $@ $^\n");
		fprintf(file, "\t$(V)echo $(GREEN)\"[$(NAME)] Library created ✅\"$(RESET)\n\n");
	}
	/* EXEC */
	else
	{
		fprintf(file, "\t$(V)$(CC) $(CFLAGS) $(LDFLAGS) $(OBJ) $(BONUS_OBJ) $(LIBS) $(MLXFLAGS) -o $(NAME)\n");
		fprintf(file, "\t$(V)echo $(GREEN)\"[$(NAME)] Executable created ✅\"$(RESET)\n\n");
	}



	/*** USE Libft ***/
	if (config->include_libft)
	{
		fprintf(file, "# Libft\n");
		fprintf(file, "$(LIBFT):\n");
		fprintf(file, "\t$(V)$(MAKE) --silent -C $(LIBFT_DIR)\n");
		fprintf(file, "\t$(V)echo '[$(NAME)] Libft build successfully'\n\n");
	}
	/*** USE MiniLibX ***/
	if (config->include_mlx)
	{
		fprintf(file, "# MiniLibX\n");
		fprintf(file, "$(MINILIBX_DIR):\n");
		fprintf(file, "\t$(V)echo '[$(NAME)] Downloading MiniLibX from github.com...'$(RESET)\n");
		fprintf(file, "\t@git clone https://github.com/42Paris/minilibx-linux.git $(MINILIBX_DIR) > /dev/null 2>&1\n");
		fprintf(file, "\t$(V)echo '[$(NAME)] Compiling MiniLibX...'$(RESET)\n");
		fprintf(file, "\t@$(MAKE) -C $(MINILIBX_DIR) > /dev/null 2>&1\n");
		fprintf(file, "\t$(V)echo '[$(NAME)] MiniLibX installed successfully'$(RESET)\n\n");
	}

	/*** BONUS RULE ***/
	if (config->src_file_bonus && strlen(config->src_file_bonus) > 0)
		fprintf(file, "bonus: $(OBJDIR) $(BONUS_OBJ) $(NAME)\n");


	/*** CLEAN RULES ***/
	fprintf(file, "# Clean Rules\n");
	fprintf(file, "clean:\n");
	fprintf(file, "\t$(V)echo $(RED)'[$(NAME)] Cleaning objects'd$(RESET)\n");
	fprintf(file, "\t$(V)rm -rf $(OBJDIR)\n\n");

	fprintf(file, "fclean: clean\n");
	fprintf(file, "\t$(V)echo $(RED)'[$(NAME)] Cleaning all files'$(RESET)\n");
	fprintf(file, "\t$(V)rm -f $(NAME)\n");
	if (config->include_libft)
		fprintf(file, "\t$(V)$(MAKE) --silent -C $(LIBFT_DIR) fclean\n");
	if (config->include_mlx)
	{
		fprintf(file, "\t$(V)echo $(RED)'[mlx] Remove directory'$(RESET)\n");
		fprintf(file, "\t@rm -rf $(MINILIBX_DIR)\n");
	}

	fprintf(file, "\nre: fclean all\n\n");


	/*** REGEN RULES ***/
	fprintf(file, "# Makefile Reconfiguration \n");
	fprintf(file, "regen:\n");
	fprintf(file, "\tmakemyfile\n\n");

	/*** PHONY ***/
	fprintf(file, ".PHONY: all clean fclean re bonus regen\n");
	fprintf(file, ".DEFAULT_GOAL := all\n");

	fclose(file);
}
